# Generated by Django 4.1 on 2025-03-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name_plural': 'authors'},
        ),
    ]
