# Generated by Django 4.1 on 2025-03-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
